project:
  type: website
  output-dir: docs

website:
  title: "Latent Tendencies"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/krishnakalyan3/blog

format:
  html:
    theme:
      light: sandstone
      dark: darkly
    css: styles.css



