project:
  type: website
  output-dir: docs

website:
  title: "Latent Tendencies"
  google-analytics: "G-2MBKRDEPBV"
  navbar:
    right:
      - about.qmd
      - text: Talks
        href: "talks.html"
      - icon: github
        href: https://github.com/krishnakalyan3/blog
      

format:
  html:
    theme:
      light: sandstone
      dark: darkly
    css: styles.css



