project:
  type: website
  output-dir: docs

website:
  title: "Krishna's Latent Tendencies"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - talks.qmd

format:
  html:
    theme: sketchy
    css: styles.css



