project:
  type: website
  output-dir: docs

website:
  title: "Krishna Kalyan"
  google-analytics: "G-2MBKRDEPBV"
  favicon: favicon.ico
  navbar:
    right:
      - icon: github
        href: https://github.com/krishnakalyan3
      - icon: twitter
        href: https://twitter.com/krishnakalyan3
      - icon: linkedin
        href: https://www.linkedin.com/in/krishnakalyan3/
      - icon: envelope
        href: mailto:krishnakalyan3@gmail.com

format:
  html:
    theme: cyborg
    css: styles.css



